rvm:
  - 2.1.10
  - 2.2.4
  - 2.3.3
  - 2.4.0
gemfile:
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
bundler_args: --no-deployment
script: bundle exec rake $TASK
env:
  global:
    - TASK=test
sudo: false
cache:
  bundler: true
branches:
  only:
    - master
matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails5.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails5.1.gemfile
  include:
    - rvm: 2.4.0
      env:
        - TASK=rubocop
