rvm:
  - 2.1.10
  - 2.2.4
  - 2.3.3
  - 2.4.0
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
bundler_args: --no-deployment
script:
  - bundle exec rake rubocop
  - bundle exec rake test
sudo: false
cache:
  bundler: true
branches:
  only:
    - master
    - 3-7-0
matrix:
  exclude:
    - rvm: 2.4.0
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails4.0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails4.1.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails5.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails5.1.gemfile
